spring:
  server:
    port: 8081
  datasource:
    url: jdbc:postgresql://localhost:5432/adeskdb?currentSchema=rep
    username: adesk_admin
    password: adesk_password
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    org.hibernate.SQL: warn
    org.flywaydb.core: info
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
